jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mostrar versión de Node.js
        run: node -v
      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Instalar dependencias
        run: npm install
